# Generated by Django 3.2.11 on 2022-03-31 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(blank=True, max_length=250)),
                ('date_add', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Carts',
                'ordering': ['date_add'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartapp.carts')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.product')),
            ],
            options={
                'db_table': 'CartItem',
            },
        ),
    ]
